-- ══════════════════════════════════════════════════════════════════════════════
-- Gods Eye Studio — Cron Jobs & Agent Pipeline Tables
-- Migration 005: Scheduled tasks, execution logs, content briefs
-- ══════════════════════════════════════════════════════════════════════════════

-- Cron Jobs: Per-user, per-brand scoped scheduled tasks
CREATE TABLE IF NOT EXISTS public.cron_jobs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  brand_id UUID DEFAULT NULL,
  task_type TEXT NOT NULL, -- research-trends, pull-analytics, weekly-strategy, auto-publish, competitor-scan, custom
  name TEXT NOT NULL,
  cron_expression TEXT NOT NULL, -- "0 15 * * *"
  config JSONB DEFAULT '{}', -- task-specific config (custom prompt, competitors list, etc.)
  timezone TEXT DEFAULT 'Asia/Kolkata',
  enabled BOOLEAN DEFAULT TRUE,
  last_run_at TIMESTAMPTZ DEFAULT NULL,
  last_run_status TEXT DEFAULT NULL, -- success, failed, skipped
  created_at TIMESTAMPTZ DEFAULT NOW(),
  updated_at TIMESTAMPTZ DEFAULT NOW()
);

-- RLS: Users can only see/modify their own jobs
ALTER TABLE public.cron_jobs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own cron jobs"
  ON public.cron_jobs FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own cron jobs"
  ON public.cron_jobs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update own cron jobs"
  ON public.cron_jobs FOR UPDATE
  USING (auth.uid() = user_id);

CREATE POLICY "Users can delete own cron jobs"
  ON public.cron_jobs FOR DELETE
  USING (auth.uid() = user_id);

-- Cron Executions: Execution history log
CREATE TABLE IF NOT EXISTS public.cron_executions (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  job_id UUID NOT NULL REFERENCES public.cron_jobs(id) ON DELETE CASCADE,
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  status TEXT NOT NULL, -- success, failed, skipped
  result JSONB DEFAULT NULL,
  error_message TEXT DEFAULT NULL,
  executed_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.cron_executions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own executions"
  ON public.cron_executions FOR SELECT
  USING (auth.uid() = user_id);

-- Content Briefs: Generated by research agent, used by creative agent
CREATE TABLE IF NOT EXISTS public.content_briefs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  brand_id UUID DEFAULT NULL,
  trend_summary TEXT,
  sources JSONB DEFAULT '[]',
  keywords TEXT[] DEFAULT '{}',
  competitor_context JSONB DEFAULT NULL,
  status TEXT DEFAULT 'pending', -- pending, in_progress, completed, rejected
  created_by TEXT DEFAULT 'manual', -- manual, cron_research_agent
  created_at TIMESTAMPTZ DEFAULT NOW()
);

ALTER TABLE public.content_briefs ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view own briefs"
  ON public.content_briefs FOR SELECT
  USING (auth.uid() = user_id);

CREATE POLICY "Users can insert own briefs"
  ON public.content_briefs FOR INSERT
  WITH CHECK (auth.uid() = user_id);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_cron_jobs_user ON public.cron_jobs(user_id);
CREATE INDEX IF NOT EXISTS idx_cron_jobs_enabled ON public.cron_jobs(enabled) WHERE enabled = TRUE;
CREATE INDEX IF NOT EXISTS idx_cron_executions_job ON public.cron_executions(job_id);
CREATE INDEX IF NOT EXISTS idx_cron_executions_user ON public.cron_executions(user_id);
CREATE INDEX IF NOT EXISTS idx_content_briefs_user ON public.content_briefs(user_id);
CREATE INDEX IF NOT EXISTS idx_content_briefs_brand ON public.content_briefs(brand_id);
